/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.proj;

import org.junit.jupiter.api.Test;

class EvaluationTest {
    @Test void appHasAGreeting() {
        Evaluation classUnderTest = new Evaluation();
    }
}
