/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.proj;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        new grammarTest().test();
    }
}
